scripts/transforms/custom-value-css-box-shadow.transform.js
scripts/transforms/custom-value-css-typography.transform.js
scripts/transforms/transforms.js

Created new transform function typograpgy tokens. Changed name for boxShadow transformations in `transforms.js` file.

feat(transforms): add new typography transform for style-dictionary

---

docs/CHANGELOG.md
scripts/transforms/custom-attributes-default.transform.js
scripts/transforms/custom-value-css-typography.transform.js
scripts/transforms/transforms.js

Added typography transform and improved attributes default transfrom contains more than 6 elements

feat(transforms): add typography transform and fix attributes default transform - DSY-1304

---

data/tokens.json

Edit description on typography.link.text.s

feat(data): edit description on typography.link.text.s

---

data/tokens.json

fixing the name of the subtitle token to be consistent wi…th other tokens

subtitle token name fix

---

data/tokens.json

@ljemmo Please can you review and merge?

feat(data): Add yin.100 token. Add utility.yin.100 token.

---

data/tokens.json

Reverts Sage/design-tokens#265

Revert "feat(data): Rename evolutive to progressive, reorder code"

---

data/tokens.json

Add a colors.utility.yang.080 reference by the color.yang.080

feat(data): Add token for Search on dark placeholder

---

data/tokens.json

Needed for Left Nav item height

feat(data): add new sizing 44px

---

data/tokens.json

As we have a new left nav we need a child background to apply

feat(data):add child bg for Left nav

---

data/tokens.json

Add action minor gray 700 for use on subtle button hover state (on darkbg)

feat(data): add minor gray hover state

---

data/tokens.json

1. Add XS size
2. change XL size to 16px (from .100 to .200)
3. change all weights to Medium (from .400 to .500)

feat(data):add and edit typography token for loader

---

data/tokens.json

- colors.utility.yin.010
- colors.utility.yang.030
Deleted as not used in any component

Feat(data): Deleted the following tokens

---

data/tokens.json

This is what I add for Tile cell fix width
sizing.2000 = 160px
sizing.2500 = 200px
sizing.3000 = 240px

feat(data): add 3 new size token for tile

---

data/tokens.json

add 1 size token for tile 7000 for 560px

feat(data): add 1 size token for tile

---

data/tokens.json

s typogrraphy token font size.010

feat(data): add 1 typogrraphy token for badge.

---

data/tokens.json

A set of color that's call notification. I duplication this from Caution, but here the main orange is "600", #BB4F00.
For easy change in future.

feat(data): add new color for badge

---

data/tokens.json

feat(data): remove unwanted token for badge notification

---

data/tokens/Components/actionpopover.json
data/tokens/Components/button.json
data/tokens/Components/container.json
data/tokens/Components/datatable.json
data/tokens/Components/nav.json
data/tokens/Modes/light.json
data/tokens/global.json
data/tokens/origin.json

WIP PR for all our new semantic multi-theme and multi-file tokens.

 !!DO NOT MERGE!! Finalised Multi-theme Semantic tokens

---

.github/workflows/lint.yaml

Ensures generates CSS is compliant for use within browsers.

ci: Run W3C validator on generated css files for distribution

---

data/tokens/components/button.json
data/tokens/components/form.json

feat(input): add input button spacing tokens for use with subtle buttons that are placed inside inputs.

Add input button tokens

---

data/tokens/components/badge.json
data/tokens/components/button.json
data/tokens/components/container.json
data/tokens/components/focus.json
data/tokens/components/form.json
data/tokens/components/link.json
data/tokens/components/logo.json
data/tokens/components/nav.json
data/tokens/components/page.json
data/tokens/components/popover.json
data/tokens/components/profile.json
data/tokens/components/progress.json
data/tokens/components/status.json
data/tokens/components/tab.json
data/tokens/components/table.json
data/tokens/context/frozenproduct.json
data/tokens/context/marketing.json
data/tokens/context/product.json
data/tokens/global/borderwidth.json
data/tokens/global/radius.json
data/tokens/global/shadow.json
data/tokens/global/size.json
data/tokens/global/space.json
data/tokens/global/typography.json
data/tokens/modes/dark.json
data/tokens/modes/light.json
data/tokens/primitives.json
data/tokens/screensize/large.json
data/tokens/screensize/small.json

chore(Convert to W3C DTCG format): read more at https://docs.tokens.studio/convert-to-dtcg-format (#415)

---

data/tokens/components/tab.json

Change baseline thickness from 4px to 2px.

fix(tab): Update value of tab.size.baseline tokens.

---

data/tokens/components/status.json

…to align icon with sage logo in global header

fix(global message): Update value of status.space.message.global.x.M to align icon with sage logo in global header

---

data/tokens/components/container.json

1. Add container.color.calendar.<hue>.bo…rder-default tokens.
2. Update values of container.color.calendar.<hue>.pattern tokens from modes.color.colorcode.<hue> rich to deep.

feat(calendar color values): Add and update color tokens

---

data/tokens/components/button.json
data/tokens/components/form.json

Plus:
Fix: Change value of button.space.toggle.button.y.S. 
Chore: Refactor color picker code to order tokens alphabetically.

feat(Toggle button): Add button.space.toggle.container.yg tokens.

---

data/tokens/components/form.json

feat(Colorpicker): Add form.size.dropdown.colorpicker.input.minwidth.

---

data/tokens/components/progress.json
data/tokens/components/status.json
data/tokens/components/table.json
data/tokens/modes/dark.json
data/tokens/modes/light.json

1. Rearrange status color tokens alphabetically in light and dark mode files and in component status file.
2. Add modes.color.status.important defaultAlt, hover, and hoverAlt.  
3. Add 4 modes.color.status.important.inverse tokens.  
4. Add many modes.color.status.custom tokens in light and dark modes.   
5. Add many status.color.pill.custom tokens.  
6. Update modes.color.status.generic.default value and description.  
7. Update value of progress.color.datavis.fg-default.
8. Update value of table.size.icon.S from 16px to 20px.
9. Add 3 modes.color.status.important tokens for defaultAlt, hover, and hoverAlt.  
10. Add 4 modes.color.status.important.inverse tokens.

feat(Colors for Pills): Add color tokens for Pill, update Table icon size, add Important status color tokens to modes.

---

data/tokens/components/form.json

feat(Date Picker): add right padding tokens so that subtle icon only buttons feel visually balanced on date picker.

---

.github/workflows/build.yaml
.github/workflows/lint.yaml
.github/workflows/validate.yml

merge back changes to ensure PRs targeting `rc-updates` branch trigger workflow runs

Merge back workflow change
